### ISSUE TITLE
Nonstandard compute mnemonics aren’t supported

### ISSUE THREAD

**Issue by tomstuart** [Ryman/hack_simulator#1]
The simulator correctly supports the exact set of _comp_ mnemonics for C-instructions listed in [chapter 4](http://nand2tetris.org/chapters/chapter%2004.pdf). It would be convenient if it also supported other mnemonics with the same meaning, specifically:
- `M+D` (meaning `D+M`)
- `M&D` (meaning `D&M`)
- `M|D` (meaning `D|M`)

This is ultimately a helpful enhancement because the translated Hack code for VM binary operations tends to have the first operand in `M` and the second in `D` (because the second operand gets read off the stack first), so the natural order of the mnemonic is `M` _op_ `D`. In the case of `sub` this order is both legitimate and semantically necessary; for `add`, `and` and `or` it isn’t mathematically important which order the operands are in, but the natural order is technically not legal according to the Hack specification, thus introducing the inconvenience of having to switch the operands around.

The Java reference implementation doesn’t care which way round `M` and `D` are, so it would be nice if the Rust implementation could be as liberal.

**Comment by Ryman** [comment]
Should be working now

**Comment by tomstuart** [comment]
Yep, all working fine. Thanks!
