### ISSUE TITLE
Vec::reserve: `usize` overflow when accessing this/that segments

### ISSUE THREAD

**Issue by tomstuart** [Ryman/hack_simulator#2]
Compiled versions of the VM `push` and `pop` instructions targeting the `this` and `that` segments cause a panic:

```
$ bundle exec rspec spec/unit --example 'push a value onto the stack from the “this” segment'
F

Failures:

  1) CodeWriter#write_push_pop when the command is a push when the segment is “this” writes assembly to push a value onto the stack from the “this” segment
     Failure/Error: expect(emulation_of(assembly)).to change_ram.from(ram_before).to(ram_after)
     RuntimeError:
       thread '<main>' panicked at 'Vec::reserve: `usize` overflow', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:330

1 example, 1 failure
```

Here’s the Hack code generated during the above example (translated from `push this 2`):

```
@THIS
D=M
@2
A=D+A
D=M
@SP
A=M
M=D
@SP
M=M+1
```

And here’s the generated test script:

```
load assembly20150324-68020-r6h2sz.asm,
output-file output20150324-68020-122ix9f,
output-list RAM[0]%D2.6.2 RAM[3]%D2.6.2 RAM[256]%D2.6.2 RAM[257]%D2.6.2 RAM[258]%D2.6.2 RAM[3000]%D2.6.2 RAM[3001]%D2.6.2 RAM[3002]%D2.6.2 RAM[3003]%D2.6.2;
set RAM[0] 258, set RAM[256] 2, set RAM[257] 3, set RAM[3] 3000, set RAM[3000] 17, set RAM[3001] 19, set RAM[3002] 23, set RAM[3003] 29,
repeat 1000 { ticktock; }
output;
```

I don’t know why this is happening. It appears to work in the Java simulator. Could it just be that `3000` is too large an address?

**Comment by Ryman** [comment]
Looked into this, it's actually due to the format string: 'D2.6.2' where RAM[3000] is actually width 9, and RAM[258] is width 8, I checked the Java implementation and they do silent truncation. e.g. if you set 'D2.3.2' for the last column you get:

```
|RAM[300|
|   29  |
```

So, I think replicating their behavior is wrong, the best course is probably to improve the error message, and update the testcase generation to have 'D2.10.2' at minimum?

**Comment by tomstuart** [comment]
Thanks, good call. I’ll update the tests.

**Comment by tomstuart** [comment]
Using `D2.10.2` (or even `D2.8.2`) as the format string for generated test scripts makes the unit tests pass, but the acceptance tests still fail because we’re using the verbatim scripts & outputs supplied by the book.

We could edit those to make them work, but maybe it would be more in the spirit of the thing to just match the behaviour of the reference implementation? e.g. the output of [`BasicTest.tst`](https://github.com/computationclub/vm-translator/blob/master/spec/acceptance/examples/BasicTest.tst) is meant to look [like this](https://github.com/computationclub/vm-translator/blob/master/spec/acceptance/examples/BasicTest.cmp).

**Comment by Ryman** [comment]
Compromised a bit, will error if a `value` is getting truncated but not a `header`. Hopefully the acceptance tests aren't totally broken!

**Comment by tomstuart** [comment]
The unit tests now all pass without modification, so that’s great.

4/5 acceptance tests are still failing with other problems, but I’ll investigate and open separate issues for those.

(Sneak preview: `BasicTest`, `PointerTest` and `StackTest` fail with…

```
thread '<main>' panicked at 'Unhandled set destination:
', src/main.rs:42
```

…and `SimpleAdd` fails with…

```
thread '<main>' panicked at 'Comparison failed at line: 0
Got: '|  RAM[0]  |RAM[256]  |'
Expected: '|  RAM[0]  | RAM[256] |'', src/main.rs:42
```

…so we’re getting closer!)

**Comment by Ryman** [comment]
I decided to not reverse engineer their padding and just make the comparison test less sensitive for the second failure. The first was just not handling newlines and such in the `output-list`.

Looking forward to the next failures!

**Comment by tomstuart** [comment]
Thanks, the padding-related issue is totally sorted now!
