### ISSUE TITLE
Format string changes are unsupported

### ISSUE THREAD

**Issue by tomstuart** [Ryman/hack_simulator#3]
For reasons that are not at all clear to me, [`StackTest.tst`](https://github.com/computationclub/vm-translator/blob/master/spec/acceptance/examples/StackTest.tst) has two rounds of `output-list`/`output`, which (I think) is responsible for this error in the Rust simulator:

```
thread '<main>' panicked at 'Format string changed after output command', src/main.rs:42
```

Is that something you can easily support?

(This is now the only failing test! :feelsgood:)

**Comment by Ryman** [comment]
:fire: Removed the error condition :fire:

**Comment by tomstuart** [comment]
```
$ bundle exec rspec
..............................................................

Finished in 5.26 seconds (files took 0.26743 seconds to load)
62 examples, 0 failures
```

:tada:

I’ve [added a link](https://github.com/computationclub/vm-translator#test-dependencies) in the `vm-translator` README so that people know they can use this as a drop-in replacement.

**Comment by Ryman** [comment]
Awesome, cheers!
