### ISSUE TITLE
.out files aren’t written on comparison failure

### ISSUE THREAD

**Issue by tomstuart** [Ryman/hack_simulator#4]
For the [vm-translator](https://github.com/computationclub/vm-translator) acceptance tests, it’s useful to be able to compare the actual emulator output against the expected one (i.e. the `.out` file against the `.cmp`) to find out exactly what’s gone wrong. When this emulator finds that the actual and expected outputs don’t match, it panics with `Comparison failed` and apparently doesn’t write the `.out` file at all. It would be great if it wrote `.out` in all cases so that the cause of the failure can be externally inspected afterwards.

**Comment by Ryman** [comment]
Should be covered now (latest nightly), there was a big coherence change in rust just as beta hit so a lot of upstream was broken/redesigned until today!

**Comment by tomstuart** [comment]
I can no longer build:

```
$ rustc --version
rustc 1.0.0-nightly (f207ecbe0 2015-04-03) (built 2015-04-03)
$ cargo run --release -j4 -- programs/Fill.hack
[…]
Compiling hack_simulator v0.0.1 (file:///Users/tom/Work/computationclub/hack_simulator)
src/simulator.rs:4:5: 4:23 error: unresolved import `piston::quack::Set`. Could not find `quack` in `piston`
src/simulator.rs:4 use piston::quack::Set;
                       ^~~~~~~~~~~~~~~~~~
src/simulator.rs:9:21: 9:27 error: unresolved import `piston::event::MaxFps`. There is no `MaxFps` in `piston::event`
src/simulator.rs:9 use piston::event::{MaxFps, Ups};
                                       ^~~~~~
src/simulator.rs:9:29: 9:32 error: unresolved import `piston::event::Ups`. There is no `Ups` in `piston::event`
src/simulator.rs:9 use piston::event::{MaxFps, Ups};
                                               ^~~
error: aborting due to 3 previous errors
Could not compile `hack_simulator`.
```

Am I doing something wrong?

**Comment by Ryman** [comment]
Ah, sorry I forgot compiling the executable wasn't covered by `cargo test` anymore in this. Fixing this now.

**Comment by Ryman** [comment]
Should be fixed now, last commit fixes running the binary on my end!

**Comment by tomstuart** [comment]
Yep, works great now (and fixes the original issue). Thanks!
